### ISSUE TITLE
Dependency Error

### ISSUE THREAD

**Issue by takumisasakura** [anphonic/NDde#4]
Error | NU1202 | Package Specshell.NDde 3.0.6 is not compatible with net5.0 (.NETCoreApp,Version=v5.0). Package Specshell.NDde 3.0.6 supports: net5.0-windows7.0 (.NETCoreApp,Version=v5.0) | mt_dde_pusher |

Isn't this weird...?

**Comment by anphonic** [comment]
not really, probably some things in .Net 5.0 that have been removed from the library. I just cloned this to here to keep a copy of the version we use.
