### ISSUE TITLE
client.Poke returns unexplained exception

### ISSUE THREAD

**Issue by welmandouh** [anphonic/NDde#5]
This just happens after a while (few minutes of running)
the exception message returned is just "NDde.Client.DdeClient"

**Comment by anphonic** [comment]
That's one thing we have an issue with quite frequently with but in awaiting the response from the AS400. I can't really say much to it since I just replicated the repo here and we use it. Time really hasn't been available to dig into it.

**Comment by welmandouh** [comment]
I'm using a dummy program on TrStation 1131 and communicating the DDE through it's emulator. Just to have something that dynamically changes the values for reading and easily displays them for writing.
